# Generated by Django 4.1.7 on 2023-04-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='bid',
            field=models.FloatField(),
        ),
    ]
