# Generated by Django 4.1.7 on 2023-04-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='category',
        ),
    ]
