# Generated by Django 4.1.7 on 2023-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_owner_alter_watchlist_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='bid',
            field=models.FloatField(),
        ),
    ]
