# Generated by Django 4.1.7 on 2023-04-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_watchlist_bid_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listing'),
        ),
    ]
