# Generated by Django 4.1.7 on 2023-04-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_watchlist_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids1', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bids'),
        ),
    ]
