# Generated by Django 4.1.7 on 2023-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_bids_alter_listing_starting_bid_alter_watchlist_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=1),
        ),
    ]
