# Generated by Django 4.1.7 on 2023-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_bids_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='bid',
            field=models.FloatField(),
        ),
    ]
