# Generated by Django 4.1.7 on 2023-04-14 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_bids_bid_alter_listing_starting_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bids',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='bids',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
