# Generated by Django 4.1.7 on 2023-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_alter_bids_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='title',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
