# Generated by Django 4.1.7 on 2023-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_bids_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
