# Generated by Django 4.1.7 on 2023-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_comments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
